version: "3"

services:
  goc:
    image: goclab/goc:latest
    command: nodeos --data-dir /opt/goc/data --config-dir /opt/goc/config --genesis-json=/opt/goc/config/genesis.json --delete-all-blocks
    hostname: goc
    ports:
      - 8888:8888
      - 9876:9876
    volumes:
      - /data/goc/testnet/data:/opt/goc/data
      - /data/goc/testnet/config:/opt/goc/config
